default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: GemPoc_development

test:
  <<: *default
  database: GemPoc_test
  username: <%= Rails.application.credentials.DB_USER %>
  password: <%= Rails.application.credentials.DB_PASSWORD %>

production:
  <<: *default
  database: GemPoc_production
  username: <%= Rails.application.credentials.DB_USER %>c
  password: <%= Rails.application.credentials.DB_PASSWORD %>
