name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Ruby (2.6)
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Setup Code Climate test-reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: Build and test with RSpec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
    - name: Publish code coverage
      run: |
        export GIT_BRANCH= main
        ./cc-test-reporter after-build -r ${{secrets.CODECLIMATE_TOKEN}}
