name: Code Climate

on:
  push:
    branches: [ main ]  # Adjust branch(es) to trigger on

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest  # Adjust runner OS if needed

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2  # Adjust Ruby version based on your Rails app

      - name: Bundle Install
        run: bundle install

      - name: Run Tests and Coverage
        run: bundle exec rails test:cov

      - name: Upload Code Coverage to CodeClimate
        uses: paambaati/codeclimate-action@v6.0.0  # CodeClimate action
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN   }}  # Replace with your ID
        with:
          coverageCommand: bundle exec rails test:cov
          coverageLocations: ./coverage/*.xml  # Adjust path if coverage reports are elsewhere
