name: Code Coverage Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: bundle install

      - name: Install SimpleCov and Uploader
        run: |
          gem install simplecov codeclimate-test-reporter

      - name: Run Tests with Coverage and Upload to CodeClimate
        run: bundle exec rails test:cov --reporter CodeClimateReporter
