name: Code Climate

on:
  push:
    branches: [ master ]  # Adjust branch(es) to trigger on

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest  # Adjust runner OS if needed

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2  # Adjust Ruby version based on your Rails app

      - name: Bundle Install
        run: bundle install

      - name: Seed Database (if needed)
        run: bundle exec rails db:seed  # Adjust command as needed

      - name: Run RSpec Tests and Coverage
        run: bundle exec rspec --format RspecJsonFormatter --out coverage/results.json

      - name: Upload Code Coverage to CodeClimate
        uses: paambaati/codeclimate-action@v6.0.0  # CodeClimate action
        env:
          CC_TEST_REPORTER_ID: your_codeclimate_reporter_id  # Replace with your ID
        with:
          coverageCommand: cat coverage/results.json  # Coverage report location
          coverageLocations: coverage/results.json  # Adjust path if needed
