name: CodeClimate
on: [push, pull_request]
jobs:
  codeclimate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run RSpec with SimpleCov
        run: |
          bundle exec rspec
      - name: Upload coverage data to CodeClimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.json
          ./cc-test-reporter upload-coverage
